apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: dc-metro-map-6ub3
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dc-metro-map-6ub3
    app.kubernetes.io/part-of: appstudio
  name: dc-metro-map-6ub3
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: dc-metro-map-6ub3
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: dc-metro-map-6ub3
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/push-pyxis-hkbi-tenant/appstudio/dc-metro-map-6ub3@sha256:20fa4c704aceaf9dc42252cbf06cdbf676eabfcedadaca9d2ac2abb27413d29e
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        - containerPort: 8081
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
